"""add content to conversation and metadata to message

Revision ID: 420bad5dd1f4
Revises: 
Create Date: 2026-07-30 14:29:37.058213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '420bad5dd1f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('conversations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('conversations', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('model_name', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('tokens_used', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('latency_ms', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('messages', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('messages', 'content',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('messages', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('messages', 'updated_at')
    op.drop_column('messages', 'created_at')
    op.drop_column('messages', 'latency_ms')
    op.drop_column('messages', 'tokens_used')
    op.drop_column('messages', 'model_name')
    op.drop_column('conversations', 'updated_at')
    op.drop_column('conversations', 'created_at')
    op.drop_column('conversations', 'content')
    # ### end Alembic commands ###
